name: Ejecutar Script Diario

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche (UTC)
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/upload-artifact@v4

      - name: Instalar Python
        uses: actions/upload-artifact@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python scripts/pruebabdmaster.py

      - name: Subir archivo generado
        uses: actions/upload-artifact@v3
        with:
          name: base_consolidada
          path: BASE_CONSOLIDADA.xlsx

