name: Ejecutar notebook diariamente

on:
  schedule:
    - cron: '0 9 * * *'  # Se ejecuta diariamente a las 9:00 UTC (ajusta según tu zona horaria)
  workflow_dispatch:  # Permite iniciar el workflow manualmente si lo deseas

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Ejecutar el notebook
        run: |
          jupyter nbconvert --to notebook --execute path/to/pruebabdmaster.ipynb --inplace
